### ISSUE TITLE
Unable to provide internal CA certificate to plugins/git container

### ISSUE THREAD

**Issue by Nikoos** [laszlocph/woodpecker#124]
Hello,

I was able to set-up SSL certificate on my woodpecker server, but also added my CA certificate directly attached in server and agent as volume.

However, when agent starts a build process, it uses "plugins/git" docker images, and I do not found a way to provide my CA certificate inside this temporary container to allow it to browse my https gitea server.

Please find below the error message:
```
fatal: unable to access 'https://gitea.local.lab/Nikos/drone-python-test2.git/': SSL certificate problem: unable to get local issuer certificate
time="2020-06-18T22:23:02Z" level=fatal msg="exit status 128"
```
I will try to update your documentation about Gitea settings as I was able to config Woodpecker for my configuration.

Best regards,

Nikos

**Comment by laszlocph** [comment]
Self signed certificates don’t scale well. I recommend using a cert from a real CA. Let’scencrypt will get you one for free.

**Comment by Nikoos** [comment]
Hello @laszlocph,

I was able to successfully recreate a plugins/git image with my internal CA (as a trusted ca certificate), now git is able to clone without SSL issue.

I have now a better understanding about plugins/git image. 

Nikos

**Comment by Nikoos** [comment]
One way for this, could be to set a variable in woodpecker agent docker-compose file that point to a local CA certificate; this variable will be then converted as a mount operation to plugins/git image when called by woodpecker agent
