### ISSUE TITLE
Bring in the UI into one repo

### ISSUE THREAD

**Issue by kevinsimper** [laszlocph/woodpecker#54]
They have to be deployed together and would seem easier to manage 😄

**Comment by laszlocph** [comment]
I'm contemplating this. The only thing that holds me back is the experience frontend devs have when they want to make a PR. Having a pure frontend repo might feel home turf, while a big repo could be intimidating.

**Comment by kevinsimper** [comment]
Unless it has a really great fake api or json files, it is much easier to make new features that way.

So that you don't have to say, this feature branch here belongs to this branch over there.

**Comment by laszlocph** [comment]
I'm almost convinced. I have another project with the setup you are proposing.. I think I will bring in the UI in the coming weeks.

**Comment by laszlocph** [comment]
In my other project this proved to be a really good setup. Working on it.
