### ISSUE TITLE
Build Patch: drone-oss-08 -> woodpecker

### ISSUE THREAD

**Issue by AkiraNorthstar** [laszlocph/woodpecker#62]
I hope this patch helps you to build woodpecker again.
Primarily I changed the import paths.
[drone-oss-08-to-woodpecker.patch.txt](https://github.com/laszlocph/woodpecker/files/3443249/drone-oss-08-to-woodpecker.patch.txt) or #63 

Regrads,
AkiraNorthstar

**Comment by laszlocph** [comment]
#65 is meant to fix this
