### ISSUE TITLE
DRONE_REPO_CONFIG doesn't work

### ISSUE THREAD

**Issue by AkiraNorthstar** [laszlocph/woodpecker#64]
The variable DRONE_REPO_CONFIG no longer works. If DRONE_REPO_CONFIG is set to something other than ".drone.yml", then woodpecker / drone-oss-08 ignores the respective repository and its changes.

**Comment by AkiraNorthstar** [comment]
Soory - My fault! Whitespace in variable

**Comment by laszlocph** [comment]
Ah okay. I wasn't aware of this var, so could have easily broke it myself :)
