### ISSUE TITLE
Race condiotion is detcted at TestFifoCancel

### ISSUE THREAD

**Issue by mhmxs** [laszlocph/woodpecker#68]
Maybe an issue maybe not, but would be nice to remove race condition from the test.

--- FAIL: TestFifoCancel (0.00s)
        fifo_test.go:280: All pipelines should be cancelled
==================
WARNING: DATA RACE
Write at 0x00c4200ca2b0 by goroutine 36:
  github.com/laszlocph/woodpecker/cncd/queue.(*fifo).Resume()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo.go:202 +0x50
  github.com/laszlocph/woodpecker/cncd/queue.TestFifoPause()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo_test.go:302 +0x50f
  testing.tRunner()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:746 +0x16c

Previous read at 0x00c4200ca2b0 by goroutine 38:
  github.com/laszlocph/woodpecker/cncd/queue.(*fifo).process()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo.go:210 +0x54

Goroutine 36 (running) created at:
  testing.(*T).Run()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:921 +0x206
  main.main()
      github.com/laszlocph/woodpecker/cncd/queue/_test/_testmain.go:66 +0x1d3

Goroutine 38 (finished) created at:
  github.com/laszlocph/woodpecker/cncd/queue.(*fifo).Push()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo.go:61 +0xa8
  github.com/laszlocph/woodpecker/cncd/queue.TestFifoPause()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo_test.go:300 +0x4f1
  testing.tRunner()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:746 +0x16c
==================
--- FAIL: TestFifoPause (0.02s)
        testing.go:699: race detected during execution of test
==================
WARNING: DATA RACE
Read at 0x00c4201101f0 by goroutine 45:
  github.com/laszlocph/woodpecker/cncd/queue.(*fifo).process()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo.go:210 +0x54

Previous write at 0x00c4201101f0 by goroutine 44:
  github.com/laszlocph/woodpecker/cncd/queue.(*fifo).Resume()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo.go:202 +0x50
  github.com/laszlocph/woodpecker/cncd/queue.TestFifoPauseResume()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo_test.go:325 +0x43c
  testing.tRunner()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:746 +0x16c

Goroutine 45 (running) created at:
  github.com/laszlocph/woodpecker/cncd/queue.(*fifo).Push()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo.go:61 +0xa8
  github.com/laszlocph/woodpecker/cncd/queue.TestFifoPauseResume()
      /Users/richard/Development/woodpecker/src/github.com/laszlocph/woodpecker/cncd/queue/fifo_test.go:324 +0x42b
  testing.tRunner()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:746 +0x16c

Goroutine 44 (running) created at:
  testing.(*T).Run()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /Users/richard/Development/common/go-1.9.7/src/testing/testing.go:921 +0x206
  main.main()
      github.com/laszlocph/woodpecker/cncd/queue/_test/_testmain.go:66 +0x1d3
==================
--- FAIL: TestFifoPauseResume (0.00s)
        testing.go:699: race detected during execution of test

**Comment by laszlocph** [comment]
Appreciate your proactivity on this. The found race condition was my mistake from recent code changes.
