### ISSUE TITLE
Add support to source branch to PR events

### ISSUE THREAD

**Issue by marcoafilho** [laszlocph/woodpecker#77]
When creating steps for `pull-request` events, it's currently not possible to identify the name of the source branch. Currently the `DRONE_BRANCH` environment variable always returns `master`.

It would be great if we could have a way to figure out what is the actual name of the branch in the PR, not the one it points to.

It seems that drone now has this feature somewhat available https://github.com/drone/drone/issues/2222#issuecomment-436833841

**Comment by laszlocph** [comment]
Released in https://github.com/laszlocph/woodpecker/releases/tag/v0.8.106
