### ISSUE TITLE
Editerconfig

### ISSUE THREAD

**Issue by kevinsimper** [laszlocph/woodpecker#97]
There is a need for a .editorconfig

Normally JavaScript is 2 spaces, so this to deal with the unusualities 😅he

**Comment by laszlocph** [comment]
:man_facepalming:

**Comment by laszlocph** [comment]
Could you review? @kevinsimper

https://github.com/laszlocph/woodpecker/pull/107/files#diff-1e70daafb475c0ce3fef7d2728279182

I never used this file myself.

**Comment by kevinsimper** [comment]
@laszlocph That solves it ✅
